// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hewenyu/todo/ent/predicate"
	"github.com/hewenyu/todo/ent/temple"
	"github.com/hewenyu/todo/ent/user"
)

// TempleQuery is the builder for querying Temple entities.
type TempleQuery struct {
	config
	ctx               *QueryContext
	order             []OrderFunc
	inters            []Interceptor
	predicates        []predicate.Temple
	withChildren      *TempleQuery
	withParent        *TempleQuery
	withOwner         *UserQuery
	withFKs           bool
	modifiers         []func(*sql.Selector)
	loadTotal         []func(context.Context, []*Temple) error
	withNamedChildren map[string]*TempleQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TempleQuery builder.
func (tq *TempleQuery) Where(ps ...predicate.Temple) *TempleQuery {
	tq.predicates = append(tq.predicates, ps...)
	return tq
}

// Limit the number of records to be returned by this query.
func (tq *TempleQuery) Limit(limit int) *TempleQuery {
	tq.ctx.Limit = &limit
	return tq
}

// Offset to start from.
func (tq *TempleQuery) Offset(offset int) *TempleQuery {
	tq.ctx.Offset = &offset
	return tq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tq *TempleQuery) Unique(unique bool) *TempleQuery {
	tq.ctx.Unique = &unique
	return tq
}

// Order specifies how the records should be ordered.
func (tq *TempleQuery) Order(o ...OrderFunc) *TempleQuery {
	tq.order = append(tq.order, o...)
	return tq
}

// QueryChildren chains the current query on the "children" edge.
func (tq *TempleQuery) QueryChildren() *TempleQuery {
	query := (&TempleClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(temple.Table, temple.FieldID, selector),
			sqlgraph.To(temple.Table, temple.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, temple.ChildrenTable, temple.ChildrenColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParent chains the current query on the "parent" edge.
func (tq *TempleQuery) QueryParent() *TempleQuery {
	query := (&TempleClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(temple.Table, temple.FieldID, selector),
			sqlgraph.To(temple.Table, temple.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, temple.ParentTable, temple.ParentColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOwner chains the current query on the "owner" edge.
func (tq *TempleQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(temple.Table, temple.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, temple.OwnerTable, temple.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Temple entity from the query.
// Returns a *NotFoundError when no Temple was found.
func (tq *TempleQuery) First(ctx context.Context) (*Temple, error) {
	nodes, err := tq.Limit(1).All(setContextOp(ctx, tq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{temple.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tq *TempleQuery) FirstX(ctx context.Context) *Temple {
	node, err := tq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Temple ID from the query.
// Returns a *NotFoundError when no Temple ID was found.
func (tq *TempleQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = tq.Limit(1).IDs(setContextOp(ctx, tq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{temple.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tq *TempleQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := tq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Temple entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Temple entity is found.
// Returns a *NotFoundError when no Temple entities are found.
func (tq *TempleQuery) Only(ctx context.Context) (*Temple, error) {
	nodes, err := tq.Limit(2).All(setContextOp(ctx, tq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{temple.Label}
	default:
		return nil, &NotSingularError{temple.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tq *TempleQuery) OnlyX(ctx context.Context) *Temple {
	node, err := tq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Temple ID in the query.
// Returns a *NotSingularError when more than one Temple ID is found.
// Returns a *NotFoundError when no entities are found.
func (tq *TempleQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = tq.Limit(2).IDs(setContextOp(ctx, tq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{temple.Label}
	default:
		err = &NotSingularError{temple.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tq *TempleQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := tq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Temples.
func (tq *TempleQuery) All(ctx context.Context) ([]*Temple, error) {
	ctx = setContextOp(ctx, tq.ctx, "All")
	if err := tq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Temple, *TempleQuery]()
	return withInterceptors[[]*Temple](ctx, tq, qr, tq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tq *TempleQuery) AllX(ctx context.Context) []*Temple {
	nodes, err := tq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Temple IDs.
func (tq *TempleQuery) IDs(ctx context.Context) ([]uint64, error) {
	var ids []uint64
	ctx = setContextOp(ctx, tq.ctx, "IDs")
	if err := tq.Select(temple.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tq *TempleQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := tq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tq *TempleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tq.ctx, "Count")
	if err := tq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tq, querierCount[*TempleQuery](), tq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tq *TempleQuery) CountX(ctx context.Context) int {
	count, err := tq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tq *TempleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tq.ctx, "Exist")
	switch _, err := tq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tq *TempleQuery) ExistX(ctx context.Context) bool {
	exist, err := tq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TempleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tq *TempleQuery) Clone() *TempleQuery {
	if tq == nil {
		return nil
	}
	return &TempleQuery{
		config:       tq.config,
		ctx:          tq.ctx.Clone(),
		order:        append([]OrderFunc{}, tq.order...),
		inters:       append([]Interceptor{}, tq.inters...),
		predicates:   append([]predicate.Temple{}, tq.predicates...),
		withChildren: tq.withChildren.Clone(),
		withParent:   tq.withParent.Clone(),
		withOwner:    tq.withOwner.Clone(),
		// clone intermediate query.
		sql:  tq.sql.Clone(),
		path: tq.path,
	}
}

// WithChildren tells the query-builder to eager-load the nodes that are connected to
// the "children" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TempleQuery) WithChildren(opts ...func(*TempleQuery)) *TempleQuery {
	query := (&TempleClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withChildren = query
	return tq
}

// WithParent tells the query-builder to eager-load the nodes that are connected to
// the "parent" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TempleQuery) WithParent(opts ...func(*TempleQuery)) *TempleQuery {
	query := (&TempleClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withParent = query
	return tq
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TempleQuery) WithOwner(opts ...func(*UserQuery)) *TempleQuery {
	query := (&UserClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withOwner = query
	return tq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Temple.Query().
//		GroupBy(temple.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tq *TempleQuery) GroupBy(field string, fields ...string) *TempleGroupBy {
	tq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TempleGroupBy{build: tq}
	grbuild.flds = &tq.ctx.Fields
	grbuild.label = temple.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Temple.Query().
//		Select(temple.FieldCreatedAt).
//		Scan(ctx, &v)
func (tq *TempleQuery) Select(fields ...string) *TempleSelect {
	tq.ctx.Fields = append(tq.ctx.Fields, fields...)
	sbuild := &TempleSelect{TempleQuery: tq}
	sbuild.label = temple.Label
	sbuild.flds, sbuild.scan = &tq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TempleSelect configured with the given aggregations.
func (tq *TempleQuery) Aggregate(fns ...AggregateFunc) *TempleSelect {
	return tq.Select().Aggregate(fns...)
}

func (tq *TempleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tq); err != nil {
				return err
			}
		}
	}
	for _, f := range tq.ctx.Fields {
		if !temple.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tq.path != nil {
		prev, err := tq.path(ctx)
		if err != nil {
			return err
		}
		tq.sql = prev
	}
	return nil
}

func (tq *TempleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Temple, error) {
	var (
		nodes       = []*Temple{}
		withFKs     = tq.withFKs
		_spec       = tq.querySpec()
		loadedTypes = [3]bool{
			tq.withChildren != nil,
			tq.withParent != nil,
			tq.withOwner != nil,
		}
	)
	if tq.withParent != nil || tq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, temple.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Temple).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Temple{config: tq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(tq.modifiers) > 0 {
		_spec.Modifiers = tq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tq.withChildren; query != nil {
		if err := tq.loadChildren(ctx, query, nodes,
			func(n *Temple) { n.Edges.Children = []*Temple{} },
			func(n *Temple, e *Temple) { n.Edges.Children = append(n.Edges.Children, e) }); err != nil {
			return nil, err
		}
	}
	if query := tq.withParent; query != nil {
		if err := tq.loadParent(ctx, query, nodes, nil,
			func(n *Temple, e *Temple) { n.Edges.Parent = e }); err != nil {
			return nil, err
		}
	}
	if query := tq.withOwner; query != nil {
		if err := tq.loadOwner(ctx, query, nodes, nil,
			func(n *Temple, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	for name, query := range tq.withNamedChildren {
		if err := tq.loadChildren(ctx, query, nodes,
			func(n *Temple) { n.appendNamedChildren(name) },
			func(n *Temple, e *Temple) { n.appendNamedChildren(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range tq.loadTotal {
		if err := tq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tq *TempleQuery) loadChildren(ctx context.Context, query *TempleQuery, nodes []*Temple, init func(*Temple), assign func(*Temple, *Temple)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*Temple)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Temple(func(s *sql.Selector) {
		s.Where(sql.InValues(temple.ChildrenColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.temple_parent
		if fk == nil {
			return fmt.Errorf(`foreign-key "temple_parent" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "temple_parent" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (tq *TempleQuery) loadParent(ctx context.Context, query *TempleQuery, nodes []*Temple, init func(*Temple), assign func(*Temple, *Temple)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*Temple)
	for i := range nodes {
		if nodes[i].temple_parent == nil {
			continue
		}
		fk := *nodes[i].temple_parent
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(temple.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "temple_parent" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (tq *TempleQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*Temple, init func(*Temple), assign func(*Temple, *User)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*Temple)
	for i := range nodes {
		if nodes[i].user_todos == nil {
			continue
		}
		fk := *nodes[i].user_todos
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_todos" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tq *TempleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tq.querySpec()
	if len(tq.modifiers) > 0 {
		_spec.Modifiers = tq.modifiers
	}
	_spec.Node.Columns = tq.ctx.Fields
	if len(tq.ctx.Fields) > 0 {
		_spec.Unique = tq.ctx.Unique != nil && *tq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tq.driver, _spec)
}

func (tq *TempleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   temple.Table,
			Columns: temple.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: temple.FieldID,
			},
		},
		From:   tq.sql,
		Unique: true,
	}
	if unique := tq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, temple.FieldID)
		for i := range fields {
			if fields[i] != temple.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tq *TempleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tq.driver.Dialect())
	t1 := builder.Table(temple.Table)
	columns := tq.ctx.Fields
	if len(columns) == 0 {
		columns = temple.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tq.sql != nil {
		selector = tq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tq.ctx.Unique != nil && *tq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tq.predicates {
		p(selector)
	}
	for _, p := range tq.order {
		p(selector)
	}
	if offset := tq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedChildren tells the query-builder to eager-load the nodes that are connected to the "children"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (tq *TempleQuery) WithNamedChildren(name string, opts ...func(*TempleQuery)) *TempleQuery {
	query := (&TempleClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if tq.withNamedChildren == nil {
		tq.withNamedChildren = make(map[string]*TempleQuery)
	}
	tq.withNamedChildren[name] = query
	return tq
}

// TempleGroupBy is the group-by builder for Temple entities.
type TempleGroupBy struct {
	selector
	build *TempleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tgb *TempleGroupBy) Aggregate(fns ...AggregateFunc) *TempleGroupBy {
	tgb.fns = append(tgb.fns, fns...)
	return tgb
}

// Scan applies the selector query and scans the result into the given value.
func (tgb *TempleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tgb.build.ctx, "GroupBy")
	if err := tgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TempleQuery, *TempleGroupBy](ctx, tgb.build, tgb, tgb.build.inters, v)
}

func (tgb *TempleGroupBy) sqlScan(ctx context.Context, root *TempleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tgb.fns))
	for _, fn := range tgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tgb.flds)+len(tgb.fns))
		for _, f := range *tgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TempleSelect is the builder for selecting fields of Temple entities.
type TempleSelect struct {
	*TempleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ts *TempleSelect) Aggregate(fns ...AggregateFunc) *TempleSelect {
	ts.fns = append(ts.fns, fns...)
	return ts
}

// Scan applies the selector query and scans the result into the given value.
func (ts *TempleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ts.ctx, "Select")
	if err := ts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TempleQuery, *TempleSelect](ctx, ts.TempleQuery, ts, ts.inters, v)
}

func (ts *TempleSelect) sqlScan(ctx context.Context, root *TempleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ts.fns))
	for _, fn := range ts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
