// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/hewenyu/todo/ent/temple"
	"github.com/hewenyu/todo/ent/user"
)

// Temple is the model entity for the Temple schema.
type Temple struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 状态
	Status temple.Status `json:"status,omitempty"`
	// 状态 正常 删除
	DeleteAt temple.DeleteAt `json:"delete_at,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TempleQuery when eager-loading is set.
	Edges         TempleEdges `json:"edges"`
	temple_parent *uint64
	user_todos    *uint64
}

// TempleEdges holds the relations/edges for other nodes in the graph.
type TempleEdges struct {
	// Children holds the value of the children edge.
	Children []*Temple `json:"children,omitempty"`
	// Parent holds the value of the parent edge.
	Parent *Temple `json:"parent,omitempty"`
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
	// totalCount holds the count of the edges above.
	totalCount [3]map[string]int

	namedChildren map[string][]*Temple
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e TempleEdges) ChildrenOrErr() ([]*Temple, error) {
	if e.loadedTypes[0] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TempleEdges) ParentOrErr() (*Temple, error) {
	if e.loadedTypes[1] {
		if e.Parent == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: temple.Label}
		}
		return e.Parent, nil
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TempleEdges) OwnerOrErr() (*User, error) {
	if e.loadedTypes[2] {
		if e.Owner == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Owner, nil
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Temple) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case temple.FieldID, temple.FieldPriority:
			values[i] = new(sql.NullInt64)
		case temple.FieldStatus, temple.FieldDeleteAt, temple.FieldText:
			values[i] = new(sql.NullString)
		case temple.FieldCreatedAt, temple.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case temple.ForeignKeys[0]: // temple_parent
			values[i] = new(sql.NullInt64)
		case temple.ForeignKeys[1]: // user_todos
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Temple", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Temple fields.
func (t *Temple) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case temple.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = uint64(value.Int64)
		case temple.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				t.CreatedAt = value.Time
			}
		case temple.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				t.UpdatedAt = value.Time
			}
		case temple.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				t.Status = temple.Status(value.String)
			}
		case temple.FieldDeleteAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delete_at", values[i])
			} else if value.Valid {
				t.DeleteAt = temple.DeleteAt(value.String)
			}
		case temple.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				t.Text = value.String
			}
		case temple.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				t.Priority = int(value.Int64)
			}
		case temple.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field temple_parent", value)
			} else if value.Valid {
				t.temple_parent = new(uint64)
				*t.temple_parent = uint64(value.Int64)
			}
		case temple.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_todos", value)
			} else if value.Valid {
				t.user_todos = new(uint64)
				*t.user_todos = uint64(value.Int64)
			}
		}
	}
	return nil
}

// QueryChildren queries the "children" edge of the Temple entity.
func (t *Temple) QueryChildren() *TempleQuery {
	return NewTempleClient(t.config).QueryChildren(t)
}

// QueryParent queries the "parent" edge of the Temple entity.
func (t *Temple) QueryParent() *TempleQuery {
	return NewTempleClient(t.config).QueryParent(t)
}

// QueryOwner queries the "owner" edge of the Temple entity.
func (t *Temple) QueryOwner() *UserQuery {
	return NewTempleClient(t.config).QueryOwner(t)
}

// Update returns a builder for updating this Temple.
// Note that you need to call Temple.Unwrap() before calling this method if this Temple
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Temple) Update() *TempleUpdateOne {
	return NewTempleClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the Temple entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Temple) Unwrap() *Temple {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Temple is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Temple) String() string {
	var builder strings.Builder
	builder.WriteString("Temple(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("created_at=")
	builder.WriteString(t.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(t.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", t.Status))
	builder.WriteString(", ")
	builder.WriteString("delete_at=")
	builder.WriteString(fmt.Sprintf("%v", t.DeleteAt))
	builder.WriteString(", ")
	builder.WriteString("text=")
	builder.WriteString(t.Text)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", t.Priority))
	builder.WriteByte(')')
	return builder.String()
}

// NamedChildren returns the Children named value or an error if the edge was not
// loaded in eager-loading with this name.
func (t *Temple) NamedChildren(name string) ([]*Temple, error) {
	if t.Edges.namedChildren == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := t.Edges.namedChildren[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (t *Temple) appendNamedChildren(name string, edges ...*Temple) {
	if t.Edges.namedChildren == nil {
		t.Edges.namedChildren = make(map[string][]*Temple)
	}
	if len(edges) == 0 {
		t.Edges.namedChildren[name] = []*Temple{}
	} else {
		t.Edges.namedChildren[name] = append(t.Edges.namedChildren[name], edges...)
	}
}

// Temples is a parsable slice of Temple.
type Temples []*Temple

func (t Temples) config(cfg config) {
	for _i := range t {
		t[_i].config = cfg
	}
}
