// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Temple is the predicate function for temple builders.
type Temple func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
